# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import proto.Authenticate_pb2 as Authenticate__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

GRPC_GENERATED_VERSION = '1.72.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in Authenticate_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AuthenticateServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SignUp = channel.unary_unary(
                '/authenticate.AuthenticateService/SignUp',
                request_serializer=Authenticate__pb2.SignUpRequest.SerializeToString,
                response_deserializer=Authenticate__pb2.SignUpResponse.FromString,
                _registered_method=True)
        self.SignIn = channel.unary_unary(
                '/authenticate.AuthenticateService/SignIn',
                request_serializer=Authenticate__pb2.SignInRequest.SerializeToString,
                response_deserializer=Authenticate__pb2.SignInResponse.FromString,
                _registered_method=True)
        self.RefreshToken = channel.unary_unary(
                '/authenticate.AuthenticateService/RefreshToken',
                request_serializer=Authenticate__pb2.RefreshTokenRequest.SerializeToString,
                response_deserializer=Authenticate__pb2.RefreshTokenResponse.FromString,
                _registered_method=True)
        self.SignOut = channel.unary_unary(
                '/authenticate.AuthenticateService/SignOut',
                request_serializer=Authenticate__pb2.SignOutRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.OAuth2Login = channel.unary_unary(
                '/authenticate.AuthenticateService/OAuth2Login',
                request_serializer=Authenticate__pb2.OAuth2LoginRequest.SerializeToString,
                response_deserializer=Authenticate__pb2.OAuth2LoginResponse.FromString,
                _registered_method=True)
        self.OAuth2Callback = channel.unary_unary(
                '/authenticate.AuthenticateService/OAuth2Callback',
                request_serializer=Authenticate__pb2.OAuth2CallbackRequest.SerializeToString,
                response_deserializer=Authenticate__pb2.OAuth2CallbackResponse.FromString,
                _registered_method=True)
        self.GetMe = channel.unary_unary(
                '/authenticate.AuthenticateService/GetMe',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=Authenticate__pb2.UserProfile.FromString,
                _registered_method=True)
        self.GetProfileByToken = channel.unary_unary(
                '/authenticate.AuthenticateService/GetProfileByToken',
                request_serializer=Authenticate__pb2.GetProfileByTokenRequest.SerializeToString,
                response_deserializer=Authenticate__pb2.UserProfile.FromString,
                _registered_method=True)


class AuthenticateServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SignUp(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SignIn(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RefreshToken(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SignOut(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OAuth2Login(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OAuth2Callback(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProfileByToken(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuthenticateServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SignUp': grpc.unary_unary_rpc_method_handler(
                    servicer.SignUp,
                    request_deserializer=Authenticate__pb2.SignUpRequest.FromString,
                    response_serializer=Authenticate__pb2.SignUpResponse.SerializeToString,
            ),
            'SignIn': grpc.unary_unary_rpc_method_handler(
                    servicer.SignIn,
                    request_deserializer=Authenticate__pb2.SignInRequest.FromString,
                    response_serializer=Authenticate__pb2.SignInResponse.SerializeToString,
            ),
            'RefreshToken': grpc.unary_unary_rpc_method_handler(
                    servicer.RefreshToken,
                    request_deserializer=Authenticate__pb2.RefreshTokenRequest.FromString,
                    response_serializer=Authenticate__pb2.RefreshTokenResponse.SerializeToString,
            ),
            'SignOut': grpc.unary_unary_rpc_method_handler(
                    servicer.SignOut,
                    request_deserializer=Authenticate__pb2.SignOutRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'OAuth2Login': grpc.unary_unary_rpc_method_handler(
                    servicer.OAuth2Login,
                    request_deserializer=Authenticate__pb2.OAuth2LoginRequest.FromString,
                    response_serializer=Authenticate__pb2.OAuth2LoginResponse.SerializeToString,
            ),
            'OAuth2Callback': grpc.unary_unary_rpc_method_handler(
                    servicer.OAuth2Callback,
                    request_deserializer=Authenticate__pb2.OAuth2CallbackRequest.FromString,
                    response_serializer=Authenticate__pb2.OAuth2CallbackResponse.SerializeToString,
            ),
            'GetMe': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMe,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=Authenticate__pb2.UserProfile.SerializeToString,
            ),
            'GetProfileByToken': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProfileByToken,
                    request_deserializer=Authenticate__pb2.GetProfileByTokenRequest.FromString,
                    response_serializer=Authenticate__pb2.UserProfile.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'authenticate.AuthenticateService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('authenticate.AuthenticateService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AuthenticateService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SignUp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/authenticate.AuthenticateService/SignUp',
            Authenticate__pb2.SignUpRequest.SerializeToString,
            Authenticate__pb2.SignUpResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SignIn(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/authenticate.AuthenticateService/SignIn',
            Authenticate__pb2.SignInRequest.SerializeToString,
            Authenticate__pb2.SignInResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RefreshToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/authenticate.AuthenticateService/RefreshToken',
            Authenticate__pb2.RefreshTokenRequest.SerializeToString,
            Authenticate__pb2.RefreshTokenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SignOut(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/authenticate.AuthenticateService/SignOut',
            Authenticate__pb2.SignOutRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OAuth2Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/authenticate.AuthenticateService/OAuth2Login',
            Authenticate__pb2.OAuth2LoginRequest.SerializeToString,
            Authenticate__pb2.OAuth2LoginResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OAuth2Callback(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/authenticate.AuthenticateService/OAuth2Callback',
            Authenticate__pb2.OAuth2CallbackRequest.SerializeToString,
            Authenticate__pb2.OAuth2CallbackResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/authenticate.AuthenticateService/GetMe',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            Authenticate__pb2.UserProfile.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProfileByToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/authenticate.AuthenticateService/GetProfileByToken',
            Authenticate__pb2.GetProfileByTokenRequest.SerializeToString,
            Authenticate__pb2.UserProfile.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
