services:
  redis:
    build:
      context: ./redis
    env_file:
      - ../.env  # Using production environment file
    volumes:
      - redis_data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    networks:
      - auth_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3

  mikhail:
    build:
      context: ./Mikhail
    env_file:
      - ../.env
    ports:
      - "50051:50051"
    networks:
      - auth_network
    depends_on:
      - redis

volumes:
  redis_data:

networks:
  auth_network:
    driver: bridge