services:
  redis:
    build:
      context: ./redis
    env_file:
      - ./prod.env  # Using production environment file
    volumes:
      - redis_data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    networks:
      - auth_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3

  auth:
    build:
      context: ./Mikhail
    env_file:
      - ./prod.env  # Using production environment file
    environment:
      - REDIS_URL=redis://redis:6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - ENCRYPTION_KEY=${REDIS_ENCRYPTION_KEY}
      - YANDEX_OAUTH_CLIENT_ID=${YANDEX_OAUTH_CLIENT_ID}
      - YANDEX_OAUTH_CLIENT_SECRET=${YANDEX_OAUTH_CLIENT_SECRET}
      - OAUTH_REDIRECTION_URL=${OAUTH_REDIRECTION_URL}
      - MIKHAIL_PORT=50051
      - ENVIRONMENT=production  # Changed to production
      - RATE_LIMIT_REQUESTS=60
      - RATE_LIMIT_WINDOW=60
    ports:
      - "${MIKHAIL_PORT}:50051"
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - auth_network

volumes:
  redis_data:

networks:
  auth_network:
    driver: bridge